GET http://localhost:3000/local/characters

###

GET http://localhost:3000/local/characters/dd2c81e7-f357-40a3-b8f8-fa62def1bdf6

###

GET http://localhost:3000/local/characters/000

###

POST http://localhost:3000/local/characters
Content-Type: application/json

{
  "characterName": "Big robot guy",
  "planet": "Sandy sand",
  "episodes": ["OLD HOPE"]
}

###

PATCH http://localhost:3000/local/characters/ad4c7d73-55d9-4eb5-bf6d-2f38d3273a4e
Content-Type: application/json

{
  "planet": "Sandy world"
}

###

DELETE http://localhost:3000/local/characters/dd2c81e7-f357-40a3-b8f8-fa62def1bdf6

