GET http://localhost:3000/dev/characters

###

GET http://localhost:3000/dev/characters/123?elo=asd

###

POST http://localhost:3000/dev/characters
Content-Type: application/json

{
  "name": "suabo",
  "age": 123
}

