service: galaxy-wars
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-central-1
  iamRoleStatements:
      - Effect: "Allow"
        Action:
        - dynamodb:Query
        - dynamodb:Scan
        Resource:
          Fn::GetAtt:
            - GalaxyCharactersTable
            - Arn

plugins:
  - serverless-express
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

functions:
  api:
    handler: src/handler.api
    events:
      - http:
          method: ANY
          path: /{proxy+}
      - http:
          method: ANY
          path: /

custom:
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

    seed:
      local:
        sources:
          - table: galaxy-characters
            sources: [./data/galaxyCharacters.json]

resources:
  Resources:
    GalaxyCharactersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: galaxy-characters
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: planet
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: planet
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
